### PR TITLE
 Feature/support feature flags decide API

### PR DESCRIPTION
**Pull request by imhmdb**
Builds on https://github.com/PostHog/posthog-php/pull/9 (to add PSR-4 support)
adds support for [feature flags decide API](https://posthog.com/docs/api/post-only-endpoints#decide)

introducing 2 new public methods for the LibCurl consumer, `fetchAllowedFeatureFlags` returns a list of allowed features for a given distinct Id, and `decide` check against that array if a key exists and returns a default value otherwise.

### CODE REVIEW

**Comment by joesaunderson** [comment]
@imhmdb is this something you would consider raising a PR to the main PostHog repo? It would address my issue here: https://github.com/PostHog/posthog-php/issues/10

**Comment by imhmdb** [comment]
> @imhmdb is this something you would consider raising a PR to the main PostHog repo? It would address my issue here: https://github.com/PostHog/posthog-php/issues/10

Hi, 
the main repo had too many neglected important PRs like the one with the PSR-4 support, by seeing that I decided to make this fork to have a proper client for our usage until that original repo is maintained properly, not using psr-4 in 2021 is a huge red flag for me.

You can use this fork or copy my work on the feature flags and open a PR as you please.

**Comment by imhmdb** [comment]
@joesaunderson btw you need this extra commit for this functionality to be exposed for usage

https://github.com/zidsa/posthog-php/commit/f963edf6fcd344c27b225e377edff05ad4b0a5c8

**Comment by yakkomajuri** [comment]
Hey @imhmdb! Yakko from PostHog here. You are absolutely right that our PHP library was a bit neglected. We've grown fast and had limited engineering capacity. However, we've now formed a team that has libraries as a key priority, and I'd love to get your changes in there! 

I'd also be happy to hook you up with some PostHog merch as a thank you!

**Comment by imhmdb** [comment]
> Hey @imhmdb! Yakko from PostHog here. You are absolutely right that our PHP library was a bit neglected. We've grown fast and had limited engineering capacity. However, we've now formed a team that has libraries as a key priority, and I'd love to get your changes in there! 
> 
> 
> 
> I'd also be happy to hook you up with some PostHog merch as a thank you!

That's really nice to hear, we recently adopted PostHog for our product analytics and feature flags and we're enjoying everything about it. We're also loving the fact that it's a django based project even more. 🥰

**Comment by joesaunderson** [comment]
> > Hey @imhmdb! Yakko from PostHog here. You are absolutely right that our PHP library was a bit neglected. We've grown fast and had limited engineering capacity. However, we've now formed a team that has libraries as a key priority, and I'd love to get your changes in there! 
> > 
> > 
> > 
> > I'd also be happy to hook you up with some PostHog merch as a thank you!
> 
> That's really nice to hear, we recently adopted PostHog for our product analytics and feature flags and we're enjoying everything about it. We're also loving the fact that it's a django based project even more. 🥰 

They've merged PSR-4 upstream now, so your feature flags work would slot in nicely 😉

**Comment by imhmdb** [comment]
> > > Hey @imhmdb! Yakko from PostHog here. You are absolutely right that our PHP library was a bit neglected. We've grown fast and had limited engineering capacity. However, we've now formed a team that has libraries as a key priority, and I'd love to get your changes in there! 
> > > 
> > > 
> > > 
> > > I'd also be happy to hook you up with some PostHog merch as a thank you!
> > 
> > That's really nice to hear, we recently adopted PostHog for our product analytics and feature flags and we're enjoying everything about it. We're also loving the fact that it's a django based project even more. 🥰 
> 
> They've merged PSR-4 upstream now, so your feature flags work would slot in nicely 😉

That's nice, I'll take a look into rebasing this from master and try to contribute to the upstream. Even though it would be a WIP as I only supported libcurl consumer.

**Pull request merged**
